### ISSUE TITLE
Remove unnecessary `pip install`

### ISSUE THREAD

**Issue by tvercaut** [anishabahl/Phantom_IAD_inputs#1]
The default google colab environment already ships with many common packages (numpy, scipy, etc).

To save time, the first cell should be removed:
```python
!pip install numpy
!pip install scipy
!pip install pandas
!pip install matplotlib
!pip install gitpython
!pip install pathlib
!pip install requests
```

**Comment by anishabahl** [comment]
I have had to leave in !pip install gitpython as this is not as standard in google colab but I have cleared the rest
